export const MAIN = {
  PHOTOS_PENDING: 'MAIN_PHOTOS_PENDNG',
  PHOTOS_SUCCESS: 'MAIN_PHOTOS_SUCCESS',
  PHOTOS_ERROR: 'MAIN_PHOTOS_ERROR',

  SEND_FEEDBACK: 'SEND_FEEDBACK',
  SEND_FEEDBACK_SUCCESS: 'SEND_FEEDBACK_SUCCESS',
  SEND_FEEDBACK_ERROR: 'SEND_FEEDBACK_ERROR',

  NEWS_PENDING: 'GET_NEWS',
  NEWS_SUCCESS: 'NEWS_SUCCESS',
  NEWS_ERROR: 'NEWS_ERROR',

  SET_FEEDBACK_INFO: 'SET_FEEDBACK_INFO',
};

export const GALLERY = {
  CATEGORIES_PENDING: 'GALLERY_CATEGORIES_PENDING',
  CATEGORIES_SUCCESS: 'GALLERY_CATEGORIES_SUCCESS',
  CATEGORIES_ERROR: 'GALLERY_CATEGORIES_ERROR',

  PHOTOS_PENDING: 'GALLERY_PHOTOS_PENDNG',
  PHOTOS_SUCCESS: 'GALLERY_PHOTOS_SUCCESS',
  PHOTOS_ERROR: 'GALLERY_PHOTOS_ERROR',

  CHANGE_CATEGORY: 'CHANGE_CATEGORY',
  LIGHTBOX_MOVE: 'LIGTHBOX_MOVE',
  LIGHTBOX_OPEN: 'LIGTHBOX_OPEN',
  LIGHTBOX_CLOSE: 'LIGTHBOX_CLOSE',
};

export const AUTH = {
  PENDING: 'AUTH_PENDING',
  SUCCESS: 'AUTH_SUCCESS',
  ERROR: 'AUTH_ERROR',
};

export const BLOG = {
  PENDING: 'ARTICLES_PENDING',
  SUCCESS: 'ARTICLES_SUCCESS',
  ERROR: 'ARTICLES_ERROR',
  ARTICLE_PENDING: 'ARTICLE_PENDING',
  ARTICLE_SUCCESS: 'ARTICLE_PENDING',
  ARTICLE_ERROR: 'ARTICLE_ERROR',
};

export const ADMIN = {
  PHOTOS_PENDING: 'ADMIN_PHOTOS_PENDNG',
  PHOTOS_SUCCESS: 'ADMIN_PHOTOS_SUCCESS',
  PHOTOS_ERROR: 'ADMIN_PHOTOS_ERROR',

  GET_PHOTO: 'GET_PHOTO',
  GET_PHOTO_SUCCESS: 'GET_PHOTO_SUCCESS',
  GET_PHOTO_ERROR: 'GET_PHOTO_ERROR',

  DELETE_PHOTO: 'DELETE_PHOTO',
  DELETE_PHOTO_SUCCESS: 'DELETE_PHOTO_SUCCESS',
  DELETE_PHOTO_ERROR: 'DELETE_PHOTO_ERROR',

  UPLOAD_PHOTO: 'UPLOAD_PHOTO',
  UPLOAD_PHOTO_SUCCESS: 'UPLOAD_PHOTO_SUCCESS',
  UPLOAD_PHOTO_ERROR: 'UPLOAD_PHOTO_ERROR',

  ADD_CATEGORY: 'ADD_CATEGORY',
  ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
  ADD_CATEGORY_ERROR: 'ADD_CATEGORY_ERROR',

  GET_CATEGORY: 'GET_CATEGORY',
  GET_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',
  GET_CATEGORY_ERROR: 'GET_CATEGORY_ERROR',

  DELETE_CATEGORY: 'DELETE_CATEGORY',
  DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
  DELETE_CATEGORY_ERROR: 'DELETE_CATEGORY_ERROR',

  UPDATE_PHOTO: 'UPDATE_PHOTO',
  UPDATE_PHOTO_SUCCESS: 'UPDATE_PHOTO_SUCCESS',
  UPDATE_PHOTO_ERROR: 'UPDATE_PHOTO_ERROR',

  FILL_PHOTO_FORM: 'FILL_PHOTO_FORM',
  FILL_CATEGORY_FORM: 'FILL_CATEGORY_FORM',

  NEWS_PENDING: 'ADMIN_NEWS_PENDING',
  NEWS_SUCCESS: 'ADMIN_NEWS_PENDING',
  NEWS_ERROR: 'ADMIN_NEWS_PENDING',

  DELETE_ARTICLE: 'ADMIN_DELETE_ARTICLE',
  DELETE_ARTICLE_SUCCESS: 'ADMIN_DELETE_ARTICLE_ERROR',
  DELETE_ARTICLE_ERROR: 'ADMIN_DELETE_ARTICLE_ERROR',

  EDIT_ARTIClE: 'ADMIN_EDIT_ARTICLE',
  SET_ACTIVE_CATEGORY: 'SET_ACTIVE_CATEGORY',
};

export const REVIEWS = {
  REVIEWS_PENDING: 'REVIEWS_PENDING',
  REVIEWS_SUCCESS: 'REVIEWS_SUCCESS',
  REVIEWS_ERROR: 'REVIEWS_ERROR',

  UPLOAD_REVIEW: 'UPLOAD_REVIEW',
  UPLOAD_REVIEW_SUCCESS: 'UPLOAD_REVIEW_SUCCESS',
  UPLOAD_REVIEW_ERROR: 'UPLOAD_REVIEW_ERROR',

  APPROVE_REVIEW: 'APPROVE_REVIEW',
  SET_EMPTY: 'SET_EMPTY',

  UPLOAD_REVIEW_IMAGE: 'UPLOAD_REVIEW_IMAGE',
  UPLOAD_REVIEW_IMAGE_SUCCESS: 'UPLOAD_REVIEW_IMAGE_SUCCESS',
  UPLOAD_REVIEW_IMAGE_ERROR: 'UPLOAD_REVIEW_IMAGE_ERROR',
};
