export const MAIN = {
  PHOTOS_PENDING: "MAIN_PHOTOS_PENDNG",
  PHOTOS_SUCCESS: "MAIN_PHOTOS_SUCCESS",
  PHOTOS_ERROR: "MAIN_PHOTOS_ERROR",

  SEND_FEEDBACK: "SEND_FEEDBACK",
  SEND_FEEDBACK_SUCCESS: "SEND_FEEDBACK_SUCCESS",
  SEND_FEEDBACK_ERROR: "SEND_FEEDBACK_ERROR",

  SET_FEEDBACK_INFO: "SET_FEEDBACK_INFO"
};

export const GALLERY = {
  CATEGOGIES_PENDING: "GALLERY_CATEGORIES_PENDING",
  CATEGOGIES_SUCCESS: "GALLERY_CATEGORIES_SUCCESS",
  CATEGOGIES_ERROR: "GALLERY_CATEGORIES_ERROR",

  PHOTOS_PENDING: "GALLERY_PHOTOS_PENDNG",
  PHOTOS_SUCCESS: "GALLERY_PHOTOS_SUCCESS",
  PHOTOS_ERROR: "GALLERY_PHOTOS_ERROR",

  CHANGE_CATEGORY: "CHANGE_CATEGORY",
  LIGHTBOX_MOVE: "LIGTHBOX_MOVE",
  LIGHTBOX_OPEN: "LIGTHBOX_OPEN",
  LIGHTBOX_CLOSE: "LIGTHBOX_CLOSE"
};

export const AUTH = {
  PENDING: "AUTH_PENDING",
  SUCCESS: "AUTH_SUCCESS",
  ERROR: "AUTH_ERROR"
};

export const ADMIN = {
  PHOTOS_PENDING: "ADMIN_PHOTOS_PENDNG",
  PHOTOS_SUCCESS: "ADMIN_PHOTOS_SUCCESS",
  PHOTOS_ERROR: "ADMIN_PHOTOS_ERROR",

  GET_PHOTO: "GET_PHOTO",
  GET_PHOTO_SUCCESS: "GET_PHOTO_SUCCESS",
  GET_PHOTO_ERROR: "GET_PHOTO_ERROR",

  DELETE_PHOTO: "DELETE_PHOTO",
  DELETE_PHOTO_SUCCESS: "DELETE_PHOTO_SUCCESS",
  DELETE_PHOTO_ERROR: "DELETE_PHOTO_ERROR",

  UPLOAD_PHOTO: "UPLOAD_PHOTO",
  UPLOAD_PHOTO_SUCCESS: "UPLOAD_PHOTO_SUCCESS",
  UPLOAD_PHOTO_ERROR: "UPLOAD_PHOTO_ERROR",

  ADD_CATEGORY: "ADD_CATEGORY",
  ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
  ADD_CATEGORY_ERROR: "ADD_CATEGORY_ERROR",

  REMOVE_CATEGORY: "REMOVE_CATEGORY",
  REMOVE_CATEGORY_SUCCESS: "REMOVE_CATEGORY_SUCCESS",
  REMOVE_CATEGORY_ERROR: "REMOVE_CATEGORY_ERROR",

  UPDATE_PHOTO: "UPDATE_PHOTO",
  UPDATE_PHOTO_SUCCESS: "UPDATE_PHOTO_SUCCESS",
  UPDATE_PHOTO_ERROR: "UPDATE_PHOTO_ERROR",

  FILL_PHOTO_FORM: "FILL_PHOTO_FORM",
  FILL_CATEGORY_FORM: "FILL_CATEGORY_FORM"
};
